version: '3.3'

services:
  server:
    container_name: pb-vue-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./pb_data:/pb_data
    env_file:
      - .env